// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI93ChCbIxBCk8fp7jGRC44O1_LEtpZnA',
    appId: '1:800963077338:web:a2aceb258c44dd4dc0f1e3',
    messagingSenderId: '800963077338',
    projectId: 'movies-app-15cb4',
    authDomain: 'movies-app-15cb4.firebaseapp.com',
    storageBucket: 'movies-app-15cb4.firebasestorage.app',
    measurementId: 'G-4EDNQGDRHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0OfrMlaWW7FfEhM3sUh5v8xjdIeAsqpU',
    appId: '1:800963077338:android:622a041ef68bfbfbc0f1e3',
    messagingSenderId: '800963077338',
    projectId: 'movies-app-15cb4',
    storageBucket: 'movies-app-15cb4.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByVDzNuwhnP0drGtzAKD4kTSeaHQY95yo',
    appId: '1:800963077338:ios:5fa4817cafa7e426c0f1e3',
    messagingSenderId: '800963077338',
    projectId: 'movies-app-15cb4',
    storageBucket: 'movies-app-15cb4.firebasestorage.app',
    iosClientId: '800963077338-hdvpaprotikmel36cu6mu1qqq6b0v6bb.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesApp',
  );
}
