// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdxSqWwHFIm431dxTFPn_1jlEraQycY74',
    appId: '1:1069182548645:web:3bacfebb2c4aaf57156b4c',
    messagingSenderId: '1069182548645',
    projectId: 'movies-app-874f9',
    authDomain: 'movies-app-874f9.firebaseapp.com',
    storageBucket: 'movies-app-874f9.firebasestorage.app',
    measurementId: 'G-8H6GKBQP2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRBB2FhdyYAQ7242EhwRjrGEUS0wtGHjA',
    appId: '1:1069182548645:android:8f96f27f87775f85156b4c',
    messagingSenderId: '1069182548645',
    projectId: 'movies-app-874f9',
    storageBucket: 'movies-app-874f9.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEcdlPPErYYre_f99pZekKImWAb1XLQcA',
    appId: '1:1069182548645:ios:8fe2c0088179b4af156b4c',
    messagingSenderId: '1069182548645',
    projectId: 'movies-app-874f9',
    storageBucket: 'movies-app-874f9.firebasestorage.app',
    iosClientId: '1069182548645-89l7tn2c12b9tj7lfq0s81kbqkrjhook.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesApp',
  );
}
